server:
  port: 9000

spring:
  application:
     name: xxl-job-admin
     version: 1.0
  profiles:
    active: dev
  freemarker:
    prefix:
    suffix: .ftl
    content-type: text/html;charset=UTF-8
    expose-spring-macro-helpers: true
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    cache: true
    order: 0
    settings:
       template_update_delay: 0
       default_encoding: UTF-8
       output_encoding: UTF-8
       locale: zh_CN
       number_format: 0.##########
       date_format: yyyy-MM-dd
       time_format: HH:mm:ss
       datetime_format: yyyy-MM-dd HH:mm:s
       classic_compatible: true
       template_exception_handler: ignore
    template-loader-path: classpath:/template/


rest:
  log:
    server:
       print-request-threshold: 11
       print-response: true
    client:
       print-request-threshold: 11
       print-response: true


